### ISSUE TITLE
Publish new version to pypi

### ISSUE THREAD

**Issue by dennisjlee** [pyepics/newportxps#19]
Would it be possible to publish a new version of this package to pypi? I noticed that the published version is from November 2020 and that there have been numerous features and bugfixes since then.
Thanks!

**Comment by newville** [comment]
@dennisjlee Thanks for the reminder.  Yes, this needs attention. I'll try to push an update this week.

**Comment by dennisjlee** [comment]
@newville thank you!

**Comment by newville** [comment]
@dennisjlee OK, I released 0.3 and pushed to PyPI.
