### ISSUE TITLE
Bug in ftp_wrapper

### ISSUE THREAD

**Issue by Nico-Helmi** [pyepics/newportxps#7]
Hello,

I wanted to use your module to control a Newport XPS-D. After having problems establishing the sftp connection I finally found the reason: In the ftp_wrapper.py file, the "connect" function trys to establish a connection to the XPS using "username=self.username" and "password=self.username" (Line 75). The latter should be changed to "password=self.password". 

Kind regards,
Nico

**Comment by newville** [comment]
@Nico-Helmi Oh, good catch - thanks.  PR would be welcome...

**Comment by Nico-Helmi** [comment]
Sure, I can (hopefully) do that!
I'm new to Github so I did not think of that.

**Comment by newville** [comment]
fixed with #8
